### ISSUE TITLE
The test website cannot sign up

### ISSUE THREAD

**Issue by fsZhuangB** [Stlouislee/ClassHelper#2]
How to implement it?

**Comment by Stlouislee** [comment]
I will design the logic later. (I'm working on STATS201 😢 ). 
Basically a `INSERT` statement...
Any idea?

**Comment by fsZhuangB** [comment]
Me too, maybe after the exam, we can do it.

Stlouislee <notifications@github.com>于2019年5月26日 周日上午10:23写道：

**Comment by Stlouislee** [comment]
The registration function has been implemented.
